import { css } from "@emotion/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { Controller } from "react-scrollmagic";
import Advice from "../components/advice/advice";
import Header from "../components/header/header";
import Heuristic from "../scene/heuristic";
import Intro from "../scene/intro";
import Skills from "../scene/skills";
import { PageInfo, PageManager, PageManagerContext } from "./util";

const pageInfo: PageInfo[] = [
  { key: "intro", component: Intro, label: "Home" },
  { key: "heuristic", component: Heuristic, label: "About" },
];

const Home: NextPage = () => {
  const pageManager = new PageManager(pageInfo.map((page) => page.key));

  useEffect(() => {
    document.addEventListener("scroll", (e) => {
      pageManager.scrollY(window.scrollY);
    });
  }, []);

  return (
    <Controller>
      <PageManagerContext.Provider value={pageManager}>
        <div css={rootStyle}>
          <Head>
            <title>portfolio depp diver</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Header pages={pageInfo} />
          <Advice />
          {pageInfo.map((page) => (
            <page.component pageKey={page.key} />
          ))}
        </div>
      </PageManagerContext.Provider>
    </Controller>
  );
};

export default Home;

const rootStyle = css`
  background-color: black;
  min-height: 200vh;
  overflow-x: clip;
`;
