import { css } from "@emotion/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import Advice from "../components/advice/advice";
import Header from "../components/header/header";
// import { ControllerContext, useControllerSetting } from "../scene/utill";
import {
  PageInfo,
  PageManager,
  PageManagerContext,
  useSetContentsPage,
} from "./util";
import Heuristic from "../scene/heuristic";
import Intro from "../scene/intro";
import Skills from "../scene/skills";
import { Controller, Scene } from "react-scrollmagic";
import Career from "../scene/career";
import gsap from "gsap";
import Transition from "../scene/transition";
import Contents from "../scene/contents";

export const pageInfo: PageInfo[] = [
  { key: "intro", component: Intro, label: "Home" },
  { key: "heuristic", component: Heuristic, label: "About" },
  { key: "career", component: Career, label: "Career" },
  { key: "skills", component: Skills, label: "Skills" },
  { key: "project", component: Contents, label: "Project" },
];

const Home: NextPage = () => {
  const pageManager = new PageManager(pageInfo.map((page) => page.key));

  useEffect(() => {
    document.addEventListener("scroll", (e) => {
      pageManager.scrollY(window.scrollY);
    });
  }, []);

  return (
    <PageManagerContext.Provider value={pageManager}>
      <Controller>
        <div css={rootStyle}>
          <Head>
            <title>portfolio depp diver</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header pages={pageInfo} />
          <Advice />

          {pageInfo.map((page) => (
            <page.component pageKey={page.key} key={page.key} />
          ))}
        </div>
      </Controller>
    </PageManagerContext.Provider>
  );
};

export default Home;

const rootStyle = css`
  background-color: black;
  min-height: 200vh;
  overflow-x: clip;
`;
